### ISSUE TITLE
Connecting controllers to server.js

### ISSUE THREAD

**Issue by kylegorjanc** [shishkina/q_cards#1]
@amcooper Hi!  I went through our server.js file and debugged over the weekend, but for some reason when I connect the controllers the server crashes over and over.  I've google searched my brains out and conferenced with the team.  We did fix one problem - requiring the files - but after another round of debugging I'm back to the same problem.  Error message below.

---

/Users/kylethegirl/Sites/qCards/q_cards/node_modules/express/lib/router/index.js:458
      throw new TypeError('Router.use() requires middleware function but got a ' + gettype(fn));
      ^

TypeError: Router.use() requires middleware function but got a Object
    at Function.use (/Users/kylethegirl/Sites/qCards/q_cards/node_modules/express/lib/router/index.js:458:13)
    at EventEmitter.<anonymous> (/Users/kylethegirl/Sites/qCards/q_cards/node_modules/express/lib/application.js:219:21)
    at Array.forEach (native)
    at EventEmitter.use (/Users/kylethegirl/Sites/qCards/q_cards/node_modules/express/lib/application.js:216:7)
    at Object.<anonymous> (/Users/kylethegirl/Sites/qCards/q_cards/server.js:40:5)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by amcooper** [comment]
OK let's look it over after stand-up :star2:
